
# SEO settings
title: "Steve Winter"
title2: "space" # default: ""
description: "Discussion on all things tech and security"
keywords: "tech, security, golang, reactjs, google, netflix"
url: https://steve-winter.github.io # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-84566934-1
repo: https://github.com/steve-winter/steve-winter.github.io
disqus_shortname: "steve-winter-github-io"
twitter_username: "stephen_winter"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Steve Winter"
  job      : "Software Engineer and Architect"
  bio      : "Designing platforms, and hacking things together for fun. "
  thumb    : /images/author.jpg
  email    : steve.winter7@gmail.com
  url      : https://steve-winter.github.io
  github   : https://github.com/steve-winter
  twitter  : https://twitter.com/stephen_winter
  # facebook : https://www.facebook.com/heiswayi.nrird
  linkedin : https://www.linkedin.com/in/stephen-winter-714aa92b

# social settings
og_locale: "en_GB"
twitter_card: "summary_large_image"
twitter_site: "@stephen_winter"

gems:
  - bourbon
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-mentions

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
